### PR TITLE
[WIP] Feature: create/list users

### PR DESCRIPTION
**Pull request by fespinoza**
## Changes:
- First implementation attempt for Index/Create Users
- Add markdown readme with sketch of implementation.
  for the user endpoints
- Treat SCIM as an acronym for rails.
- Add rspec gem with rake and dummy project setup.
- Add dummy app for testing the engine.
- Add pry for debugging.

### CODE REVIEW

**Comment by fespinoza** [comment]
@nashby this is my idea of pluggable engine for the SCIM API,

i need to define the readme, but the idea is to specify by configuration:
- your User model class
- your UserConversor class, that knows how to convert between SCIM::User and your model

the main idea is to treat `User` and `SCIM::User` as data and use classes like `UserConversor` or `UserRepository` in order to manipulate them and encapsulate their logic.

**Comment by fespinoza** [comment]
so to add this to a new project, the user only has to:
- specify the configuration of "bridge classes"
- implement a valid user conversor

**Comment by dgilperez** [comment]
Hi! 

I'm possibly tasked with integrating with a scim provider. Did you manage to have this working? Are you planning to continue working on this? 

Thanks!

**Comment by fespinoza** [comment]
personally i won't be working on this project, maybe hyper does

**Pull request closed without merging**
